#!/usr/bin/env bash
# Run a gNB + N UEs (Standalone, rfsimulator) with per-UE ray-traced channels
# and per-UE inter-cell interference noise floors from the twin.
#
# =============================================================================
# NOT VERIFIED IN THE CLOUD SANDBOX. Requires a full Linux host with root (for
# network namespaces / `ip`), a built OAI (bash oai/setup_oai.sh), and a running
# 5G core (bash oai/setup_cn5g.sh). The cloud sandbox lacks `ip`/netns and root,
# so this is validated on a host. Commands follow OAI's multi-UE SA tutorial.
# =============================================================================
#
# Per-UE channel: the gNB conf must @include the channelmod block generated by
#   python3 oai/interference_floor.py <channel_dir>     (interference_floor.conf)
# whose models rfsimu_channel_ue0, ue1, ... are matched to clients in connection
# order, so each UE gets its own noise floor. Site-specific taps come from
#   python3 oai/cfr_to_oai_channel.py <channel_dir> ...  (OAI_RT_TAPS)
#
# Usage:
#   sudo NUE=3 GNB_CONF=/abs/gnb_sa.conf UE_CONF=/abs/ue.conf \
#        OAI_RT_TAPS=/abs/oai_rt_taps.txt bash oai/run_multi_ue_rfsim.sh [duration]
set -euo pipefail

OAI_DIR="${OAI_DIR:-$HOME/openairinterface5g}"
BUILD="$OAI_DIR/cmake_targets/ran_build/build"
NUE="${NUE:-3}"
DURATION="${1:-60}"
OUT_DIR="${OUT_DIR:-$(pwd)/oai_run_multi}"
GNB_CONF="${GNB_CONF:?set GNB_CONF to an SA gNB conf that @includes interference_floor.conf}"
UE_CONF="${UE_CONF:?set UE_CONF to a UE conf}"

[ "$(id -u)" -eq 0 ] || { echo "run as root (network namespaces need it)"; exit 1; }
[ -x "$BUILD/nr-softmodem" ] || { echo "OAI not built; run oai/setup_oai.sh"; exit 1; }
command -v ip >/dev/null 2>&1 || { echo "'ip' not found (needs a full host)"; exit 1; }
mkdir -p "$OUT_DIR"; cd "$BUILD"

[ -n "${OAI_RT_TAPS:-}" ] && export OAI_RT_TAPS && echo "[multi-ue] injecting RT taps from $OAI_RT_TAPS"

echo "[gNB] starting (SA, rfsim server) ..."
./nr-softmodem -O "$GNB_CONF" --sa --rfsim --telnetsrv --telnetsrv.listenport 9090 \
    "--rfsimulator.[0].serveraddr" server > "$OUT_DIR/gnb.log" 2>&1 &
GNB=$!
sleep 8

# One namespace + UE per client; connection order maps to rfsimu_channel_ue{i}.
PIDS=()
for i in $(seq 1 "$NUE"); do
  ns="ue$i"
  ip netns add "$ns" 2>/dev/null || true
  echo "[UE $i] starting in namespace $ns ..."
  ip netns exec "$ns" "$BUILD/nr-uesoftmodem" -O "$UE_CONF" --sa --rfsim \
      --rfsimulator.options chanmod \
      --uicc0.imsi "00101000000000$i" \
      "--rfsimulator.[0].serveraddr" 127.0.0.1 \
      > "$OUT_DIR/ue$i.log" 2>&1 &
  PIDS+=("$!")
  sleep 2
done

echo "[run] capturing for ${DURATION}s ..."
sleep "$DURATION"

kill "${PIDS[@]}" "$GNB" 2>/dev/null || true
sleep 2
for i in $(seq 1 "$NUE"); do ip netns del "ue$i" 2>/dev/null || true; done

echo "Logs in $OUT_DIR/. Parse per-UE KPIs: python3 oai/collect_kpis.py $OUT_DIR/gnb.log"
